### ISSUE TITLE
Tidak dapat melakukan pengunggahan diatas 500kb

### ISSUE THREAD

**Issue by kwhandy** [agusmakmun/django-image-optimizer#5]
Saya menggunakan pillow namun ketika mencoba melakukan pengunggahan dengan file diatas 500kb server terus memberikan 502 Bad Gateway walaupun saya sudah meningkatkan client_max_sizeblablabla di server nginx

**Comment by agusmakmun** [comment]
@kwhandy halo mas, mohon maaf responsenya agak lama, saya barusan melakukan pengujian upload image ~800kb dengan pillow tdk ada masalah. Jika kasusnya di server, maka kemungkinan besar karena ada limit tertentu di servernya. Untuk melakukan pengujian, coba melakukan upload image diatas 500kb pada models yg tdk menggunakan `OptimizedImageField`.

**Comment by kwhandy** [comment]
Ok mas makasih!
