### ISSUE TITLE
Providing new option for image_optimizer method

### ISSUE THREAD

**Issue by yeole-rohan** [agusmakmun/django-image-optimizer#6]
Hi, I am working on a large project which has multiple media (image) uploads to the platform. I found your app as a good and quick to optimize the images. however would like to create a issue, feature request to you regarding following.

Currently the image_optimizer only takes size as tuple of two values, width and height. Can we implement a way for taking x and y values to too, so that cropping of image can be done from particular point on x and y axis.

Would like to know your thoughts on this, would be happy to contribute.

Thanks looking forward.

**Comment by agusmakmun** [comment]
@yeole-rohan currently we didn't support to crop the image by using axis.
for the fast response might this answer will help you (by using Pillow) https://stackoverflow.com/a/20361739/6396981

meanwhile, if you have any MR that related with this,
I'll be happy to support it as well.

---

for example:

```python
from image_optimizer.fields import OptimizedImageField
from .yourpackage import custom_image_optimizer


class CustomOptimizedImageField(OptimizedImageField):
    """An ImageField that gets optimized on save() using tinyPNG."""

    def save_form_data(self, instance, data):
        """Remove the OptimizedNotOptimized object on clearing the image."""
        # Are we updating an image?
        updating_image = True if data and getattr(instance, self.name) != data else False

        if updating_image:
            data = custom_image_optimizer(...)

        super().save_form_data(instance, data)
```

**Comment by yeole-rohan** [comment]
Will try to do so, in sometime.
thanks for letting me know.

**Comment by yeole-rohan** [comment]
Hi, Hope you are doing well.
I have created a pull request for above issue. the given function is tested
and working well with pillow.

please have a review on this in sometime.

**Comment by agusmakmun** [comment]
hello @yeole-rohan thank you for creating new MR, we appreciate about your nice contribution 🙌 
can you please also provide an unitest for that as well?

**Comment by yeole-rohan** [comment]
@agusmakmun will push a demo app for this!

**Comment by yeole-rohan** [comment]
@agusmakmun I have created a demo app inside yours demo app.

This app defined basic upload and cropping of image through axis.

- Its on developer to user cropping library and how to pass x,y from image to our function.
- I personally suggest cropper.js for this.

let me know if changes required.
looking ahead to merge.

**Comment by agusmakmun** [comment]
hello @yeole-rohan, thank so much for your contribution, we have merged your PR: #7 to #8
and I have pushed to new tag as well, you can try:

```
pip install django-image-optimizer --upgrade
```

then;

```python
from image_optimizer.utils import crop_image_on_axis

...
```

for more: https://github.com/agusmakmun/django-image-optimizer/blob/132722918bd2fc4ee2082693c98b3bc34733fdc0/image_optimizer/utils.py#L118-L126

**Comment by yeole-rohan** [comment]
Thank You so much for merging the PR. sure will try that in my code for
current project.

Looking forward for next open source project contribution.

is it okay to spread a word on LinkedIn for this project?

**Comment by agusmakmun** [comment]
yeah, that's fine. and really appreciate if you doing that. 🙌
